### ISSUE TITLE
自定义 SCWS 词库为啥不起作用？

### ISSUE THREAD

**Issue by benxiaojun** [hightman/xunsearch#101]
修改了`$prefix/etc/dict_user.txt`文件
增加了一个词“人武部”
重启了搜索服务`$prefix/bin/xs-ctl.sh -s search restart`
查询用的是`$xs->addQueryString('title:'.$kw,XS_CMD_QUERY_OP_OR);`
但是输入“人武部”搜不到对应的记录。为啥？ @hightman

**Comment by TangMonk** [comment]
1. 尝试放到 `$prefix/etc/{app}/dict_user.txt`下面
2. 放好后重建索引，`php Indexer.php  --clean`

**Comment by benxiaojun** [comment]
解决了，词库是有“人武部”这个词的，只是需要自定义词频值以增加权重；
比如标题为“一手新人武部......”，之前的权重优先级应该是“新人”>"人武部"，所以搜“人武部”搜不到，搜“新人”可以。把“人武部”的词频值设置高一点就可以了。
