### ISSUE TITLE
搜索时,tmp/search.log提示xapian exception (ERROR:Expected block 1029 to be level 2, not 0)

### ISSUE THREAD

**Issue by h23438163** [hightman/xunsearch#111]
搜索某一个库的数据时,如果是拼音,其他库会有搜索建议,这个库没有搜索建议 ,并且 tmp/search.log里会有一个报错是 : xapian exception (ERROR:Expected block 1029 to be level 2, not 0).
请问如何解决 谢谢

**Comment by hightman** [comment]
可能是数据文件损坏了，建议完整重建索引
