### ISSUE TITLE
通过docker安装的xunsearch没有生成log_db

### ISSUE THREAD

**Issue by xiaochong0302** [hightman/xunsearch#113]
直接在 ubuntu下安装的没有问题，使用 hightman/xunsearch 镜像在 docker 中 不会生成log_db，搜索和生成索引正常

报错如下：ERROR [sock:7] xapian exception (ERROR:Couldn't stat 'data/course/log_db')

**Comment by hightman** [comment]
等一段时间看看

发自我的 iPhone6艹
