### ISSUE TITLE
安装xunsearch报错

### ISSUE THREAD

**Issue by ouyangfangyuan** [hightman/xunsearch#121]
bufferevent_openssl.c:237:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:228:19: error: storage size of 'methods_bufferevent' isn't known
 static BIO_METHOD methods_bufferevent = {
                   ^~~~~~~~~~~~~~~~~~~

**Comment by ouyangfangyuan** [comment]
我在网上搜索：发现是libevent和openssl不匹配，我想问一下这个libevent大版本可以选择码？

**Comment by hightman** [comment]
2.0.x 系列都可以

发自我的 iPhone6艹
