### ISSUE TITLE
php 8.1 support

### ISSUE THREAD

**Issue by sweetrice** [hightman/xunsearch#130]
PHP message: PHP Fatal error:  During inheritance of ArrayAccess: Uncaught [XSErrorException] ../../../..(712): Return type of XSDocument::offsetExists($name) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice(8192)

**Comment by pkuoliver** [comment]
希望能够解决

**Comment by flyinghail** [comment]
https://github.com/hightman/xunsearch/pull/129
