### ISSUE TITLE
标点符号问题

### ISSUE THREAD

**Issue by zhangyue0503** [hightman/xunsearch#134]
无法使用标点符号搜索啊？
 (、!、* 这些英文标点符号直接搜索就是全部的
查看 getQuery() ，貌似标点符号直接全被过滤掉了

**Comment by hightman** [comment]
目前确实是这样处理的，什么场景需要检索标点符号呢。原定目标是语义检索

**Comment by zhangyue0503** [comment]
> 目前确实是这样处理的，什么场景需要检索标点符号呢。原定目标是语义检索

感谢回复，那会刚开始学搜索引擎相关的内容，现在了解是什么情况了，谢谢
