### ISSUE TITLE
官方的demo搜索居然也不准确

### ISSUE THREAD

**Issue by thinkpost** [hightman/xunsearch#139]
测试官方的demo居然结果页这么的不准确，http://www.xunsearch.com/demo/search.php
搜索‘条’居然没有包含'长条'的结果,这玩意确定能用？
![QQ截图20221105155626](https://user-images.githubusercontent.com/59718780/200109991-5890944b-55cc-4c1c-8388-049e87f35198.png)
![QQ截图20221105155647](https://user-images.githubusercontent.com/59718780/200109994-dd4d6a8d-9588-4b7a-8f7f-f6064f1701ac.png)

**Comment by hightman** [comment]
你可能对“全文检索”有所不明白，全文检索不是 `strstr()`
