### ISSUE TITLE
怎样做全站搜索？

### ISSUE THREAD

**Issue by lichunqiang** [hightman/xunsearch#14]
站内有文章、问答等多个模块
怎样做全站的搜索？

还是针对每个模块都建立自己的project， 在全站搜索的时候自己做处理，把分块的搜索数据进行处理汇总展示？
望指教

**Comment by hightman** [comment]
两种方法都可以，如果模块间数据差异不大可以汇总加标识处理，数据差别很大呈现效果也各不相同则建议分项目。

**Comment by lichunqiang** [comment]
Thanks, 已采用非别处理的方式，借鉴了segmentfault的搜索的那种设计实现

**Comment by weifanfou** [comment]
@lichunqiang @hightman 

能说明下怎么处理的分project的吗

同时对多个project进行搜索求出总量？然后分页怎么处理啊
