### ISSUE TITLE
安装过程时间很长，然后无响应，也不报错

### ISSUE THREAD

**Issue by aiddroid** [hightman/xunsearch#18]
在CentOS 6.6 x32上安装，默认配置，很长时间后还卡在Compiling & installing xapian-core-scws，也不报错，CPU，内存占用正常，不知道什么原因

[code]
[root@centos-web xunsearch-full-1.4.9]# sudo ./setup.sh 

+==========================================+
| Welcome to setup xunsearch(full)         |
| 欢迎使用 xunsearch (完整版) 安装程序     |
+------------------------------------------+
| Follow the on-screen instructions please |
| 请按照屏幕上的提示操作以完成安装         |
+==========================================+

Please specify the installation directory
请指定安装目录 (默认为中括号内的值)
[/usr/local/xunsearch]:

Confirm the installation directory
请确认安装目录：/usr/local/xunsearch [Y/n]

Checking scws ... 1.2.3-dev
Checking scws dict ... ok
Checking libuuid ... yes: /usr/local/xunsearch
Checking xapian-core-scws ... no
Installing xapian-core-scws (1.2.20) ... 
Extracting xapian-core-scws package ...
Configuring xapian-core-scws ...
Compiling & installing xapian-core-scws ...
[/code]

**Comment by hightman** [comment]
开启另一个窗口，检查安装目录下的 setup.log
