### ISSUE TITLE
xunsearch可以支持类似mysql的order by a+b的排序方式吗？setMultiSort方法貌似不行

### ISSUE THREAD

**Issue by lyongdee** [hightman/xunsearch#20]

**Comment by hightman** [comment]
就是 setMultiSort ，怎么不行。前提是 a 一样才考虑 b 啊。

Best Regards

hightman/海鳗
**********************************
微信/微博：hightman
Github：https://github.com/hightman

**Comment by lyongde** [comment]
您说的是在正常排序是这样没有问题的，a一样考虑b，但是mysql还有一种排序是两个字段相加再后进行，xunsearch可以支持这种方式吗，实际项目中会遇到这种情况的，貌似sphinx可以支持。

**Comment by hightman** [comment]
那就变通一下，所谓的计算权重不可能有固定的模式啊。

变通后生成一个字段来存放，表示顺序


Best Regards

hightman/海鳗
**********************************
微信/微博：hightman
Github：https://github.com/hightman

**Comment by lyongde** [comment]
嗯，是的，现在是这样处理的。

**Comment by ouewqa** [comment]
我目前也碰到这样的问题。

sphinx支持SPH_SORT_EXTENDED

支持权值计算，比如：

最近的一天发布的文章，10分，两天内的，5分，一周内的，1分。
被点赞超过>10次的，10分，>5次的，8分，>1次的，1分
更多组合排序条件

sphinx中可以做到这样计算排序。不知道xunsearch有没有这样的功能？
