### ISSUE TITLE
在什么地方可以调整建立索引的速度

### ISSUE THREAD

**Issue by shoutrain** [hightman/xunsearch#27]
现在用xunsearch，发现建立索引到能搜索，快接近1分钟了，请问如何调整建立索引的速度？

**Comment by hightman** [comment]
你用什么方式建的，接口可以 XSIndex::flushIndex，工具可以用 Indexer.php —flush

Best Regards

hightman/海鳗
**********************************
微信/微博：hightman
Github：https://github.com/hightman

**Comment by shoutrain** [comment]
我是直接的调用接口，如果用flushIndex() ，是不是就通知马上建立索引，这个方法是同步还是异步的？如果我每次新增或修改一个索引，每次都调用flushIndex，是否会造成调用端的效率底下？

**Comment by hightman** [comment]
仍然是异步，但会立即处理，否则会自动延迟好几分钟。

发自我的 iPhone6艹
