### ISSUE TITLE
xunsearch是否支持同一个字段的两次range搜索

### ISSUE THREAD

**Issue by shoutrain** [hightman/xunsearch#28]
xunsearch是否支持同一个字段的两次range搜索？比如，有个字段是age，我能否这样搜索：10 < age < 15 and 20 < age < 25?

**Comment by hightman** [comment]
可以吧。

Best Regards

hightman/海鳗
**********************************
微信/微博：hightman
Github：https://github.com/hightman

**Comment by shoutrain** [comment]
我看了官网的文档，支持addRange接口，但是这个接口只能放置一个字段的范围，如果是在一个搜索中对统一字段连续调用两个addRange赋予不同的范围，那么这两个addRange是or还是and关系？

我猜，是不是Xpian支持这种搜索，但XunSearch还对应的接口？

	/**
	 * 添加搜索过滤区间或范围
	 * @param string $field
	 * @param mixed $from 起始值(不包含), 若设为 null 则相当于匹配 <= to (字典顺序)
	 * @param mixed $to 结束值(包含), 若设为 null 则相当于匹配 >= from (字典顺序)
	 * @return XSSearch 返回对象本身以支持串接操作
	 */
	public function addRange($field, $from, $to)
	{
		if ($from === '' || $from === false) {
			$from = null;
		}
		if ($to === '' || $to === false) {
			$to = null;
		}
		if ($from !== null || $to !== null) {
			if (strlen($from) > 255 || strlen($to) > 255) {
				throw new XSException('Value of range is too long');
			}
			$vno = $this->xs->getField($field)->vno;
			$from = XS::convert($from, 'UTF-8', $this->_charset);
			$to = XS::convert($to, 'UTF-8', $this->_charset);
			if ($from === null) {
				$cmd = new XSCommand(XS_CMD_QUERY_VALCMP, XS_CMD_QUERY_OP_FILTER, $vno, $to, chr(XS_CMD_VALCMP_LE));
			} elseif ($to === null) {
				$cmd = new XSCommand(XS_CMD_QUERY_VALCMP, XS_CMD_QUERY_OP_FILTER, $vno, $from, chr(XS_CMD_VALCMP_GE));
			} else {
				$cmd = new XSCommand(XS_CMD_QUERY_RANGE, XS_CMD_QUERY_OP_FILTER, $vno, $from, $to);
			}
			$this->execCommand($cmd);
		}
		return $this;
	}

**Comment by shoutrain** [comment]
这么看来，我必须要直接调用XSCommand才能实现同一字段的两次不同范围的或搜索，对吗？

**Comment by shoutrain** [comment]
直接用Xapian的搜索语句，比如：age: 15..25 + age: 45..60

**Comment by shoutrain** [comment]
@hightman 问过国外的论坛，在Xapian上是可以直接支持age:15..25 OR age:35..45这种搜索语句的。但是我用XunSearch不可以，我是在增加一些索引后，在demo上测试的，如下：
util/Quest.php demo "chrono:1314336167..1314337169 OR chrono:1314341167..1314343169"
上面这条语句，OR前面或后面都可以单独查询出结果，但是一起就没有结果了。

**Comment by hightman** [comment]
你可以用 XSSearch:addRange 啊，放在 query 里解析似乎 不会成功。

Best Regards

hightman/海鳗
**********************************
微信/微博：hightman
Github：https://github.com/hightman

**Comment by shoutrain** [comment]
@hightman 虽然没试过，但是addRange两次，是OR关系还是AND关系呢？想到这个就觉得addRange是不是有问题？或者有地方设置默认的关系？

**Comment by hightman** [comment]
确实不行，add range 固定为 op_filter 关系 （即AND）
parse_query 印象中是不支持2次的。

Best Regards

hightman/海鳗
**********************************
微信/微博：hightman
Github：https://github.com/hightman

**Comment by shoutrain** [comment]
@hightman 好的，谢谢，那我研究一下Xapian和其PHP接口，您觉得有可能实现我想要的功能吗？如果有可能我们可以放到XunSearch中。

**Comment by hightman** [comment]
自己构建 Xapian::Query 肯定可以啊，只是xs这要相互通讯有点麻烦。xs每次add query都是在基础query上，而不能分离它们。

比如：当前是 q1，此时添加为 q1 and q2，再以or 添加 q3 就变成 (q1 AND q2) OR q3 而无法做到 q1 AND (q2 OR q3)


Best Regards

hightman/海鳗
**********************************
微信/微博：hightman
Github：https://github.com/hightman

**Comment by shoutrain** [comment]
@hightman 好的，我来尝试一下，我给您的邮箱发了我的微信，希望微信能让沟通效率高一点。我现在正在CentOS 7上装Xapian.
