### ISSUE TITLE
缓存检测

### ISSUE THREAD

**Issue by kalsolio** [hightman/xunsearch#29]
检测程序 不支持php内置的 Zend OPcache
实际运行是不是也不支持呢
// check cache
function check_cache()
{
	$rec = array();
	if (function_exists('apc_fetch')) {
		$rec[] = 'apc';
	}
	if (function_exists('xcache_get')) {
		$rec[] = 'xcache';
	}
	if (function_exists('eaccelerator_get')) {
		$rec[] = 'eAccelerator';
	}
	if (count($rec) === 0) {
		return 'WARNING';
	}
	return current($rec);
}

**Comment by kalsolio** [comment]
private function loadIniFile($file)
	{
		$cache = false;
		$cache_write = '';
		if (strlen($file) < 255 && file_exists($file)) {
			$cache_key = md5(__CLASS__ . '::ini::' . realpath($file));
			if (function_exists('apc_fetch')) {
				$cache = apc_fetch($cache_key);
				$cache_write = 'apc_store';
			} elseif (function_exists('xcache_get') && php_sapi_name() !== 'cli') {
				$cache = xcache_get($cache_key);
				$cache_write = 'xcache_set';
			} elseif (function_exists('eaccelerator_get')) {
				$cache = eaccelerator_get($cache_key);
				$cache_write = 'eaccelerator_put';
			}


确实不支持啊

**Comment by hightman** [comment]
zend opcache 不支持缓存变量啊。
