### ISSUE TITLE
xs-import -Q -m3 好久好久。。

### ISSUE THREAD

**Issue by kalsolio** [hightman/xunsearch#30]
480w数据
xs-import -Q -m3 data/order/db.re tmp/order_db.snd
导入之后 就一致在运行 这个进程的速度有什么办法可以提高吗？
提高计算机的什么配置 可以提高这个步骤的速度呢
主要是什么制约了这个进程的速度呢？

**Comment by hightman** [comment]
主要是数据量的大小、硬盘的速度、内存的容量决定的。熟练架构的情况下，尽可能切分小库，最后再用 `bin/xapian-compact` 合并。
