### ISSUE TITLE
setLimit 最大只能输出100个结果 无法再多了。

### ISSUE THREAD

**Issue by kalsolio** [hightman/xunsearch#32]
setLimit 最大只能输出100个结果 无法再多了。
XS.php貌似没有限制 是服务本身限制的吗？怎么不限制呢？

**Comment by hightman** [comment]
这是server代码中限定的，只有修改 `src/task.h` 中的 `MAX_SEARCH_RESULT` 才能调整。这是我们认为较为合理的平衡值。
