### ISSUE TITLE
xunsearch 不支持groupby吗？

### ISSUE THREAD

**Issue by nishuisanqian** [hightman/xunsearch#37]
php util/Indexer.php --project=course --rebuild --source=mysql://root:*******@127.0.0.1:3306/***** --sql="select c.id,subject_id,c.detail,course_name,c.cover,price,edu_fund_enable,c.hot,c.appraise_nums,c.appraise_score,c.student_nums,o.organ_name,f.name fitage_name,s.name subject_name from ue_course c left join ue_organ o on c.organ_id=o.id left join ue_fitage f on c.fitage_id=f.id left join ue_subject s on c.subject_id=s.id left join ue_course_mark cm on c.id=cm.course_id left join ue_mark m on m.id=cm.mark_id where cm.course_id=c.id group by cm.id"  

以上sql在mysql上没问题可以查询到记录，但是创建索引时显示只导入一条记录

**Comment by itbdw** [comment]
我16年咨询的问题，至今未果。给作者充了钱，也没反应。。。

推荐使用 elasticsearch
