### ISSUE TITLE
安装时出错ERROR: failed to compile libevent, see 'setup.log' for more detail

### ISSUE THREAD

**Issue by XQ-quadrant** [hightman/xunsearch#38]
Checking xapian-core-scws ... 1.2.22
Checking libevent ... no
Installing libevent (2.0.21-stable) ... 
Extracting libevent package ...
Configuring libevent ...
Compiling & installing libevent ...
-----
 static BIO_METHOD methods_bufferevent = {
                   ^~~~~~~~~~~~~~~~~~~
Makefile:793: recipe for target 'bufferevent_openssl.lo' failed
make[2]: *** [bufferevent_openssl.lo] Error 1
make[2]: Leaving directory '/home/xq/workspace/xunsearch-full-1.4.10/libevent-2.0.21-stable'
Makefile:857: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/xq/workspace/xunsearch-full-1.4.10/libevent-2.0.21-stable'
Makefile:1182: recipe for target 'install' failed
make: *** [install] Error 2
-----
ERROR: failed to compile libevent, see 'setup.log' for more detail

**Comment by itbdw** [comment]
我16年咨询的问题，至今未果。给作者充了钱，也没反应。。。

推荐使用 elasticsearch
