### ISSUE TITLE
1.4.10使用php脚本建索引会有内存溢出的问题。

### ISSUE THREAD

**Issue by herenet** [hightman/xunsearch#41]
PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 2840240 bytes) in /data/wwwroot/www.hongren.com/ThinkPHP/Library/Vendor/Xunsearch/XS.php on line 1379

**Comment by terryzwt** [comment]
这个你应该可以在 php.ini 或者在索引脚本执行前,手工调大 php 执行内存值.

更好的办法,个人觉得可以分多批更新索引.

**Comment by herenet** [comment]
查了一下原因，是PHP机制的问题。在递归方法中反复给同一个变量赋值造成内存溢出了。
