### ISSUE TITLE
Yii2-SDK中的ActiveRecord是否可以将components key设定为变量，不要写死

### ISSUE THREAD

**Issue by lyt8384** [hightman/xunsearch#44]
https://github.com/hightman/xunsearch/blob/28e3f312da2073948c049abe26ded2d2f9efafa6/sdk/php/wrapper/yii2-ext/ActiveRecord.php#L57

Yii2-SDK中的ActiveRecord是否可以将components name设定为变量，不要写死，这样方便定制的时候不用xunsearch做key的小伙伴。

**Comment by hightman** [comment]
那你继承生成 Search Model 的时候覆写啊
