### ISSUE TITLE
搜索语句的长度现在是192 吧，可是还是不够用，不知道可以不可以在给个对外的接口去自定义这个 属性呢？

### ISSUE THREAD

**Issue by ycll** [hightman/xunsearch#52]
如题，望尽快回复，谢谢

**Comment by ycll** [comment]
@hightman 您好！这个问题可以指导一下吗！

**Comment by hightman** [comment]
可以用 addQueryString 和 addQueryTerm 拆份组合更长的语句

Best Regards

hightman/海鳗
**********************************
微信/微博：hightman
Github：https://github.com/hightman

**Comment by ycll** [comment]
@hightman  感谢感谢
