### ISSUE TITLE
1.4.12好像有BUG

### ISSUE THREAD

**Issue by lichifeng** [hightman/xunsearch#68]
原使用版本1.4.11一切正常，更新1.4.12后出现莫名BUG，具体表现为：用显然能得到结果的关键字搜索的时候返回0条结果，换回1.4.11恢复正常。
原因不明。不知道再提供什么信息能有帮助。
不过我可以重现问题。

我使用在我的网站上 http://aocrec.com
可以用关键字"IORI"和"BT4"进行搜索，正常是有结果的（都已加入用户字典），换成1.4.12后没结果。
http://aocrec.com/debug
这是我自用的调试页面，不知道对你们有没有用。

**Comment by hightman** [comment]
删除并更新到1.4.13吧，建议用docker 否则需要自己删除include/xapian 再安装

发自我的 iPhone6艹

**Comment by lichifeng** [comment]
试了一下正常了
