### ISSUE TITLE
拜托把之前官网的的bbs开一下吧，有很大用处

### ISSUE THREAD

**Issue by Veitor** [hightman/xunsearch#83]
之前bbs里有很多帖子都有用，都是之前使用者交流讨论的结果。。
对于后续遇到问题的人来说可以有用
不知道为什么关了。。就算不让发新帖，至少留个存档可以查阅吧。。
现在遇到问题啥都搜不到了。。

**Comment by mrdznet** [comment]
是啊，赞同！

**Comment by hightman** [comment]
备案问题有很多spam信息就关了先。

**Comment by TangMonk** [comment]
确实，谷歌到很多信息都是bbs的，然后打不开

**Comment by hightman** [comment]
spam太多所以才关掉；要么明天我改个只读模式打开吧

发自我的 iPhone6艹

**Comment by TangMonk** [comment]
@hightman 
thanks!
