### ISSUE TITLE
2万多条数导入，为啥索引的时候只有100多条

### ISSUE THREAD

**Issue by wbteve** [hightman/xunsearch#90]
[root@jhSrvData demo]# /usr/local/xunsearch/sdk/php/util/Indexer.php --rebuild   --source=mysql://coreseek:xxxx@172.31.44.1:39666/biz_skyfire/ --sql=' SELECT * FROM `artViewSuss`  ' --project=demo
开始重建索引 ...
初始化数据源 ... mysql://coreseek:xxxx@172.31.44.1:39666/biz_skyfire/ 
开始批量导入数据 (请直接输入数据) ...
报告：累计已处理数据 10000 条 ...
报告：累计已处理数据 20000 条 ...
完成索引导入：成功 25933 条，失败 0 条
完成重建索引 ...

**Comment by wbteve** [comment]
大约有22项符合查询结果，库内数据总量为107项。（搜索耗时：0.0035秒） [XML]

**Comment by hightman** [comment]
导入成功至完成索引建立有一定延迟的，应稍后再测试
