### ISSUE TITLE
fpm add_dict 不起效果

### ISSUE THREAD

**Issue by angelandy** [hightman/xunsearch#96]
$so = scws_new();
        $so->set_charset('utf8');
        $so->set_ignore(true);
        $so->set_dict('/usr/local/scws/bin/dict.utf8.xdb',SCWS_XDICT_XDB);
        $so->add_dict('/usr/local/scws/bin/model_brand.xdb',SCWS_XDICT_XDB);
        $so->send_text($list[0]['content']);
        $new_arr = array();
        while ($tmp = $so->get_result())
        {
            print_r($tmp);
        }
        $so->close();
        var_dump($new_arr);

$so->add_dict('/usr/local/scws/bin/model_brand.xdb',SCWS_XDICT_XDB);
在php cli 下 有效果 
在fpm 下没有效果

**Comment by angelandy** [comment]
找到原因了,, 原来是词库权限问题

**Comment by TheBlueSkim** [comment]
建议如果问题处理了把issue关闭一下。。
